package android.emu6502

enum class AddressingMode {
  MODE_ABSOLUTE,
  MODE_ABSOLUTEX,
  MODE_ABSOLUTEY,
  MODE_ACCUMULATOR,
  MODE_IMMEDIATE,
  MODE_IMPLIED,
  MODE_INDEXEDINDIRECT,
  MODE_INDIRECT,
  MODE_INDIRECTINDEXED,
  MODE_RELATIVE,
  MODE_ZEROPAGE,
  MODE_ZEROPAGEX,
  MODE_ZEROPAGEY
}